import { ArrowDownRight, ArrowUpRight, Code2, Download } from 'lucide-react'
import { portfolio } from '../data/portfolio'
import { ProjectsPreview } from './Projects'

function AIVisual() {
  return <div className="hero-visual-wrap"><div className="profile-frame"><img src="/profile.png" alt="Nagendra Kushwaha" onError={(event) => { event.currentTarget.style.display = 'none'; event.currentTarget.nextElementSibling?.removeAttribute('hidden') }} /><div className="profile-missing" hidden>Place the portrait at <b>public/profile.png</b></div></div><div className="ai-image-frame"><img src="/ai-visual.png" alt="AI core connected to ML, NLP, LLM, data, DL, and RAG" onError={(event) => { event.currentTarget.style.display = 'none'; event.currentTarget.nextElementSibling?.removeAttribute('hidden') }} /><div className="ai-image-missing" hidden>Place the AI visual at <b>public/ai-visual.png</b></div></div></div>
}

function SectionTitle({ number, title, copy }) { return <div className="section-title"><span className="section-number">{number}</span><div><h2>{title}</h2>{copy && <p>{copy}</p>}</div></div> }

export function Home({ onNavigate }) {
  return <main>
    <section className="light-hero content-width"><div className="hero-left"><p className="overline"><span className="orange-dot" /> AI / ML ENGINEER · B H O P A L, I N D I A</p><h1>Building intelligent systems with <em>AI</em>, Machine Learning &amp; Generative AI.</h1><p className="hero-copy">AI/ML Engineer &amp; Data Scientist building intelligent systems with Machine Learning, Deep Learning &amp; Generative AI.</p><div className="hero-buttons"><a className="accent-button" href="#projects" onClick={(event) => { event.preventDefault(); onNavigate('/projects') }}>View projects <ArrowUpRight size={16} /></a><a className="soft-button" href="#skills" onClick={(event) => { event.preventDefault(); onNavigate('/skills') }}>Explore skills</a><a className="text-button" href={portfolio.personal.github} target="_blank" rel="noreferrer"><Code2 size={16} /> GitHub</a><a className="text-button" href="/resume/Nagendra_Kushwaha_AI_ML_Resume.pdf" target="_blank" rel="noreferrer"><Download size={16} /> Resume</a></div><div className="hero-note"><span>01</span><span>Learning by building</span><span>Scroll to explore <ArrowDownRight size={15} /></span></div></div><AIVisual /></section>
    <section className="light-band content-width" id="about"><SectionTitle number="01" title="A builder at the intersection of data and intelligence." copy="Strong foundations, useful artifacts, and an honest eye on what comes next." /><div className="home-about-grid"><p>I build machine learning and AI systems across data analysis, recommendation systems, NLP, deep learning, and generative AI. My focus is understanding the complete workflow, from data preparation and model development to evaluation and practical deployment.</p><div className="mini-facts"><div><span>Studying</span><b>B.Tech in Computer Science Engineering</b><small>{portfolio.personal.university}</small></div><div><span>Focus</span><b>Machine Learning · Deep Learning · NLP</b><small>Generative AI · LLM applications</small></div></div></div></section>
    <section className="home-projects content-width" id="projects"><div className="section-heading-row"><SectionTitle number="02" title="Selected work." copy="A few projects from the path so far." /><button className="text-button" onClick={() => onNavigate('/projects')}>View all projects <ArrowUpRight size={16} /></button></div><ProjectsPreview onDetails={(project) => onNavigate(`/projects/${project.id}`)} /></section>
    <section className="light-band content-width" id="skills"><div className="section-heading-row"><SectionTitle number="03" title="A toolkit in progress." copy="Capabilities are represented as working knowledge, not inflated percentages." /><button className="text-button" onClick={() => onNavigate('/skills')}>View all skills <ArrowUpRight size={16} /></button></div><div className="skill-preview-row">{portfolio.skills.slice(0, 6).map((item) => <span key={item.name}><b>{item.name}</b><small>{item.level}</small></span>)}</div></section>
    <section className="experience-home content-width" id="experience"><SectionTitle number="04" title="Learning in public, building in practice." copy="Experience that keeps the technical work grounded." /><div className="experience-home-grid">{portfolio.experience.map((item) => <article className="experience-item" key={item.company}><span>{item.date}</span><h3>{item.role}</h3><b>{item.company}</b><p>{item.details}</p></article>)}<article className="education-home"><span>Education</span><h3>B.Tech — Computer Science Engineering</h3><p>{portfolio.personal.university}</p><div><b>7.85 / 10</b><small>CGPA · 3rd Year / 6th Semester</small></div></article></div></section>
    <section className="journey-home content-width" id="journey"><SectionTitle number="05" title="One layer at a time." copy="Python and data first. Intelligent applications next." /><div className="journey-line">{portfolio.journey.map((step, index) => <span key={step}><i>{String(index + 1).padStart(2, '0')}</i><b>{step}</b></span>)}</div><div className="explore-strip"><span className="overline">Currently exploring</span><p>{portfolio.exploring.slice(0, 6).map((topic, index) => <span className="explore-topic" key={topic}><b>{topic}</b>{index < 5 && '  ·  '}</span>)}</p></div></section>
    <section className="light-contact content-width" id="contact"><div><p className="overline">06 / Contact</p><h2>Let&apos;s build<br /><em>something intelligent.</em></h2><p className="contact-copy">Open to opportunities, collaborations, and interesting AI/ML projects.</p></div><div className="contact-panel"><a href={`mailto:${portfolio.personal.email}`}>Email me / {portfolio.personal.email} <ArrowUpRight size={16} /></a><a href={portfolio.personal.github} target="_blank" rel="noreferrer">GitHub / Nagendrakushwa <ArrowUpRight size={16} /></a><a href={portfolio.personal.linkedin} target="_blank" rel="noreferrer">LinkedIn / Nagendra Kushwaha <ArrowUpRight size={16} /></a><a href="/resume/Nagendra_Kushwaha_AI_ML_Resume.pdf" target="_blank" rel="noreferrer">Resume / View PDF <ArrowUpRight size={16} /></a></div></section>
  </main>
}
